version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db

  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: nutriplanner
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: nutriplanner_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
