name: CI

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'  # Remplace par ta version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Pylint
        run: |
          pylint --rcfile=.pylintrc backend/app

      - name: Run tests with coverage
        run: |
          coverage run -m pytest --cov-config=.coveragerc --cov=backend/app
          coverage report  # Display in console
